name: Generate README and scaladoc
on:
  workflow_call:
    inputs:
      author_name: 
        required: true
        type: string
      author_email: 
        required: true
        type: string
    secrets:
      PAT:
        required: true

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git fetch --tags --unshallow -f
      - name: Setup scala
        uses: olafurpg/setup-scala@v13
      - name: Generate README
        run: sbt dynver docs/mdoc 
      - name: Commit README changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: ${{ inputs.author_name }}
          author_email: ${{ inputs.author_email }}
          message: 'Update README'
          add: '*.md'
      - name: Publish API documentation on Github
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "> Publish GitHub Pages"
          sbt makeSite publishToGitHubPages   
    